// solid-js/src/App.jsx
import { createSignal, Show } from "solid-js";
import logo from "./logo.svg";
import "./App.css";

function App() {
  const [count, setCount] = createSignal(0);

  return (
    <div class="App">
      <header class="App-header">
        <img src={logo} class="App-logo" alt="logo" />
        <p>Hello Vite + Solid!</p>
        <p>
          <button type="button" onClick={() => setCount((count) => count + 1)}>
            count is: {count()}
          </button>
        </p>
        <Show when={count() > 0}>
          <p>
            <code>The count is now: {count()}</code>
          </p>
        </Show>
        <p>
          Edit <code>App.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            class="App-link"
            href="https://www.solidjs.com/tutorial"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn Solid
          </a>
          {" | "}
          <a
            class="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;

// react-ts/src/App.tsx
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>Hello Vite + React!</p>
        <p>
          <button type="button" onClick={() => setCount(() => count + 1)}>
            count is: {count}
          </button>
        </p>
        {count > 0 ? (
          <p>
            <code>The count is now: {count}</code>
          </p>
        ) : null}
        <p>
          Edit <code>App.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          {' | '}
          <a
            className="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;
